### ISSUE TITLE
Written / expressed mandate

### ISSUE THREAD

**Issue by knut-erik** [equinor/api-strategy#1]
Formulate a written mandate for the team.

**Comment by oyron** [comment]
Dette ser veldig bra ut!
Et par kommentarer:
- Under Deliverables, mangler vi ikke her et punkt på _policy/guidelines_? Slike ting som design, arkitektur, versjonering, livssyklushåndtering, auth, etc?
- Går det an å snike inn en linje om at APIer er mer enn REST?
- I det første punktet under how we work synes jeg det vil være klargjørende å skyte inn "up front" etter "plot"
- Spottet noen små stavefeil her og der, e.g. APIs is -> APIs _are_, resently -> recently, accelrate -> accelerate, continous -> continuous, documetation -> documentation, shold -> should

**Comment by knut-erik** [comment]
Rewrote section about api policies - 45b7eaa4c65994eddf81987bc8b2b7f2c96d79f1

**Comment by knut-erik** [comment]
CIT MC will be informed about the mandate 14th Nov. There is no need for decision from CIT MC on the mandate, however when  there is a delivery on strategy (whatever artifact) I would like to promote this delivery to CIT MC for decision.

**Comment by oyron** [comment]
Mandate created. Revisions should be handled in a separate issue
