### ISSUE TITLE
API visibility

### ISSUE THREAD

**Issue by pgdr** [equinor/api-strategy#32]
The APIs should be visible for everyone, even for those who do not have access to use the APIs.

It is beneficial for developers to see existing APIs so that they know what they need to apply for.

**Comment by jokva** [comment]
I think that's a very good idea.

**Comment by pgdr** [comment]
Any progress on this issue?

**Comment by oyron** [comment]
This is a good idea and I have discussed this with the APIM team.
We agree that we want as much visibility as possible on api.equinor.com
- Public APIs (when we get some) should be visible for everyone
- Equinor-internal APIs should be visible for everyone logged into api.equinor.com
- App-internal APIs (e.g. APIs optmized for a particular client), or APIs where the API metadata is restricted/confidential may have visibility limited to selected users
- For Partner APIs you currently have to either make it publicly visible or limit visibility and add partner users to Equinor AD

The API development teams ultimately decides the visibility for their APIs, but the APIM team will go through all APIs in APIM and challenge visibility. They will also do this for new APIs.
