### ISSUE TITLE
Comments to API strategy - draft

### ISSUE THREAD

**Issue by arildeikeland** [equinor/api-strategy#37]
Ref email "API Strategy - Draft - provide feedback", please find feedback from Omnia Core Data team below;

**Suggested sections**
 - API high level architecture
   - architecture diagram/pattern - the Equinor way
   - Ref; https://www.infolob.com/how-to-plan-your-api-management-strategy/

 - API Security
   - Authentication
   - Authorisation
   - Secure communication

**Comments**
Swap order of following sections?
 - API Management tools and roles
 - API design

REST; https://github.com/equinor/api-strategy/blob/master/docs/strategy-draft.md#rest 
- Include short introduction to REST - or references to
 - HTTP as transport protocol
   - should it be: HTTPS as transport protocol ?
 - Subsection on standard operations - ref CRUD - guidelines on verbs

API First; https://github.com/equinor/api-strategy/blob/master/docs/strategy-draft.md#api-first
 - Consider including this in Goals section; https://github.com/equinor/api-strategy/blob/master/docs/strategy-draft.md#goals

Our ref; https://github.com/equinor/Omnia/issues/1191

**Comment by oyron** [comment]
Thanks for great feedback!

Some comments from me:

API high level architecture - I think the link you are referring to is describing API Management Architecture. We haven't looked into this part in the API Strategy yet. My impression have so far been that the OMNIA API/Core team has approached this in a good way, by learning and improving the setup in steps. We're open to including this in a future version of the strategy. I have added it to the issue list, and will initiate the discussion at a later stage.

**Comment by oyron** [comment]
API security is absolutely something we need to discuss. We don't have time to address this properly in the first version, but is probably the first issue to cover after v1 release. Added as an issue.

Swap order - I will have to think about that..

REST intro or reference - great comment. Will be added in v1. Issue created.

**Comment by oyron** [comment]
Adding API First as a goal - I have to think about that one as well
