### ISSUE TITLE
Notification system to announce planned & unplanned downtime

### ISSUE THREAD

**Issue by jgvabo** [equinor/api-strategy#38]
A system should be in place to post and retrieve information about planned and unplanned downtime of APIs.

The value from a user perspective is as follows

**User story**
As a user of application X
I would like to be informed about planned and unplanned downtime of data providers in the application X
In order to
Plan my usage around planned downtime, and during unplanned downtime have trust that someone knows about the issue and that steps are taken to fix it.

**Comment by oyron** [comment]
This is a valid question, and an important part of treating the API as a product.
I guess this is a similar challenge as developers of end user apps are facing when communicating with their users.
What about using existing communication channels? Slack for communicating with API client developers and Teams for communicating with end users? For external developers and end users you could use email or possibly Teams there as well.

**Comment by jgvabo** [comment]
Communication with the end-users should be from within the products, and this is why we need this service.

I dont see the Teams/Slack way as I viable way to communicate with the 1800 users that have access to our application. 

Furthermore, I don't want to mass mail all of them whenever one of our data providing APIs from third parties are down, as this will unnecessarily erode trust in our product (most mails would be about problems!).

**Comment by oyron** [comment]
I don't see why you would want to expose planned downtime of source APIs directly to your users. I think it is better that you collect this information and translate it to unambiguous message to the users, which you then communicate in the same way as other messages. 
So, I agree to disagree :)

**Comment by oyron** [comment]
This came to a conclusion - closing
