### ISSUE TITLE
OWASP Input Validation Cheat Sheet - broken link

### ISSUE THREAD

**Issue by arildeikeland** [equinor/api-strategy#80]
Hi,

Ref; section https://github.com/equinor/api-strategy/blob/master/docs/strategy.md#input-validation

Link to [OWASP Input Validation Cheat Sheet](https://owasp.org/www-project-cheat-sheets/cheatsheets/Input_Validation_Cheat_Sheet) seems to be broken, assume new link is;
<https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html>

Regards,
-Arild

**Comment by oyron** [comment]
Thanks @arildeikeland !
I have updated the document with the correct link.
